# Convert the flags variables to lists to work with target_compile_options.
function(zcnes_compile_options TARGET)
    if(MSVC)
        if(ZCNES_MSVC_FLAGS)
            separate_arguments(ZCNES_MSVC_FLAGS_LIST NATIVE_COMMAND ${ZCNES_MSVC_FLAGS})
            target_compile_options(${TARGET} PRIVATE ${ZCNES_MSVC_FLAGS_LIST})
        endif()
    else()
        if(ZCNES_GCC_CLANG_FLAGS)
            separate_arguments(ZCNES_GCC_CLANG_FLAGS_LIST NATIVE_COMMAND ${ZCNES_GCC_CLANG_FLAGS})
            target_compile_options(${TARGET} PRIVATE ${ZCNES_GCC_CLANG_FLAGS_LIST})
        endif()
    endif()
endfunction()