name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            c_compiler: clang-18
            cxx_compiler: clang++-18
            ninja_archive: ninja-linux

          - os: windows-latest
            c_compiler: clang
            cxx_compiler: clang++
            ninja_archive: ninja-win

    steps:
      - uses: actions/checkout@v4

      - name: Install Ninja
        # The shell needs to be bash for this step to work on Linux and Windows.
        shell: bash
        run: |
          curl -L -o ${{ matrix.ninja_archive }}.zip https://github.com/ninja-build/ninja/releases/download/v1.12.1/${{ matrix.ninja_archive }}.zip
          unzip ${{ matrix.ninja_archive }}.zip -d bin
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH

      - name: Configure
        run: cmake -S . -B build -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=${{matrix.c_compiler}} -DCMAKE_CXX_COMPILER=${{ matrix.cxx_compiler }}

      - name: Build
        run: cmake --build build

      - name: Test
        run: ctest --test-dir build --output-on-failure -j 2