name: CI

on:
  push:
    branches:
      - main

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Clang 17
        # The commands are from https://apt.llvm.org.
        run: | 
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh ${{ matrix.compiler.version }}

      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=clang++-17

      - name: Build
        run: cmake --build build -j 2

      # TODO: Consider making zcnes-tests a submodule. I went with a separate
      # repo for now since it's less coupled.
      - name: Clone zcnes-tests
        run: git clone https://github.com/zachcmadsen/zcnes-tests.git ../zcnes-tests 

      - name: Test
        run: ctest --test-dir build -j 2 --output-on-failure