name: CI

on:
  push:
    branches:
      - main

jobs:
  linux:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        include:
          - c_compiler: "clang-17"
            cxx_compiler: "clang++-17"
          - c_compiler: "gcc-14"
            cxx_compiler: "g++-14"

    steps:
      - uses: actions/checkout@v4

      - name: Install Ninja
        run: |
          curl -L -o ninja-linux.zip https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-linux.zip
          unzip ninja-linux.zip -d bin
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH

      - name: Configure
        run: cmake -S . -B build -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=${{matrix.c_compiler}} -DCMAKE_CXX_COMPILER=${{ matrix.cxx_compiler }} 

      - name: Build
        run: cmake --build build

      - name: Test
        run: ctest --test-dir build --output-on-failure -j 2

  # windows:
  #   runs-on: windows-latest

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Configure
  #       run: cmake --preset ci-windows

  #     - name: Build
  #       run: cmake --build build --config Release
      
  #     - name: Clone zcnes-tests
  #       run: git clone https://github.com/zachcmadsen/zcnes-tests.git ../zcnes-tests 

  #     - name: Test
  #       run: ctest --test-dir build --output-on-failure -j 2